server.port: 5555
spring:
  application.name: discovery-server
  profiles.default: local

eureka.client:
  fetch-registry: false
  register-with-eureka: false
  serviceUrl:
    defaultZone: ${EUREKA_SERVER_URL:http://localhost:5555}/eureka/
