server.port: 5050

spring:
  application.name=: config-server
  cloud.config.server.git.uri: https://github.com/KhusainovFarrukh/dedilemma-backend-configs

eureka.client.serviceUrl:
  defaultZone: ${EUREKA_SERVER_URL:http://localhost:5555}/eureka/

---
spring.config.activate.on-profile: docker
eureka.client.serviceUrl:
  defaultZone: http://dedilemma-discovery-server:5555/eureka/